routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\ForgotPasswordController;
use App\Http\Controllers\ResetPasswordController;
use App\Http\Controllers\LogoutController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\ChangePasswordController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\BrandController;
use App\Http\Controllers\UnitOfMeasurementController;
use App\Http\Controllers\ItemController;
use App\Http\Controllers\IncomeTransactionController;
use App\Http\Controllers\IncomeTransactionItemController;
use App\Http\Controllers\ExpenditureTransactionController;
use App\Http\Controllers\ExpenditureTransactionItemController;
use App\Http\Controllers\StockController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\ApplicationController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware(['guest'])->group(function () {
    Route::controller(LoginController::class)->group(function () {
        Route::get('', 'view')->name('login');
        Route::post('', 'authenticate')->middleware('throttle:5,1')
                                        ->name('authenticate');
    });

    Route::prefix('forgot-password')->group(function () {
        Route::controller(ForgotPasswordController::class)->group(function () {
            Route::get('', 'view')->name('forgot-password.index');
            Route::post('', 'sendEmail')->middleware('throttle:5,1')
                                        ->name('forgot-password.send');
        });
    });

    Route::prefix('reset-password')->group(function () {
        Route::controller(ResetPasswordController::class)->group(function () {
            Route::get('{token}', 'view')->name('reset-password.index');
            Route::post('', 'reset')->middleware('throttle:5,1')
                                    ->name('reset-password.reset');
        });
    });
});

Route::middleware(['auth'])->group(function () {
    Route::middleware(['can:isAdmin'])->group(function () {
        Route::resource('categories', CategoryController::class)->except([
            'show'
        ]);
    
        Route::resource('brands', BrandController::class)->except([
            'show'
        ]);
    
        Route::resource('unit-of-measurements', UnitOfMeasurementController::class)->except([
            'show'
        ]);
    
        Route::get('items/{id}/image', [ItemController::class, 'openImage']);

        Route::resource('users', UserController::class);

        Route::controller(ApplicationController::class)->group(function () {
            Route::get('application', 'edit')->name('application.edit');
            Route::put('application', 'update')->name('application.update');
        });
    });

    Route::post('logout', [LogoutController::class, 'logout'])
            ->name('logout');

    Route::get('dashboard', [DashboardController::class, 'index'])
            ->name('dashboard');

    Route::controller(ProfileController::class)->group(function () {
        Route::get('profile', 'edit')->name('profile.edit');
        Route::put('profile', 'update')->name('profile.update');
    });

    Route::controller(ChangePasswordController::class)->group(function () {
        Route::get('change-password', 'edit')->name('change-password.edit');
        Route::put('change-password', 'update')->name('change-password.update');
    });

    Route::resource('items', ItemController::class);
    
    Route::delete('income-transaction-items/{item_id}/create', [
        IncomeTransactionItemController::class, 'deleteCreateSession'
    ])->name('income-transaction-items.delete-create-session');

    Route::delete('income-transaction-items/{income_transaction_id}/{item_id}', [
        IncomeTransactionItemController::class, 'deleteEditSession'
    ])->name('income-transaction-items.delete-edit-session');

    Route::resource('income-transaction-items', IncomeTransactionItemController::class)->except([
        'show', 'index'
    ]);

    Route::resource('income-transactions', IncomeTransactionController::class);

    Route::delete('expenditure-transaction-items/{item_id}/create', [
        ExpenditureTransactionItemController::class, 'deleteCreateSession'
    ])->name('expenditure-transaction-items.delete-create-session');

    Route::delete('expenditure-transaction-items/{expenditure_transaction_id}/{item_id}', [
        ExpenditureTransactionItemController::class, 'deleteEditSession'
    ])->name('expenditure-transaction-items.delete-edit-session');

    Route::resource('expenditure-transaction-items', ExpenditureTransactionItemController::class)->except([
        'show', 'index', 'delete'
    ]);

    Route::resource('expenditure-transactions', ExpenditureTransactionController::class);

    Route::get('stocks', [StockController::class, 'index'])->name('stocks.index');
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'username',
        'role',
        'password',
        'created_at',
        'updated_at'
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime'
    ];

    /**
     * The storage format of the model's date columns.
     *
     * @var string
     */
    protected $dateFormat = 'U';

    /**
     * Indicates if the model should be timestamped.
     *
     * @var bool
     */
    public $timestamps = false;

    public static function getData($input)
    {
        $data = self::select(
            'id', 'name', 'username', 'email',
            'role'
        )
        ->where('id', '!=', auth()->user()->id);

        if (!empty($input['keyword'])) {
            $data->where(function ($query) use ($input) {
                $query->where('name', 'LIKE', '%' . $input['keyword'] . '%')
                        ->orWhere('username', 'LIKE', '%' . $input['keyword'] . '%')
                        ->orWhere('email', 'LIKE', '%' . $input['keyword'] . '%')
                        ->orWhere('role', 'LIKE', '%' . $input['keyword'] . '%');
            });
        }

        if (!empty($input['role'])) {
            $data->where('role', '=', $input['role']);
        }

        $orderColumns = [
            'name', 'email', 'username', 'role'
        ];

        if (in_array($input['order_by'], $orderColumns)) {
            if ($input['order_direction'] === 'asc' || $input['order_direction'] === 'desc') {
                $data->orderBy($input['order_by'], $input['order_direction']);
            } else {
                $data->orderBy($input['order_by']);
            }
        } else {
            $data->orderBy('name', 'asc');
        }

        return $data->offset($input['offset'])
                        ->limit(10)
                        ->get();
    }

    public static function countData($input)
    {
        $data = self::select('id')
                    ->where('id', '!=', auth()->user()->id);

        if (!empty($input['keyword'])) {
            $data->where(function ($query) use ($input) {
                $query->where('name', 'LIKE', '%' . $input['keyword'] . '%')
                        ->orWhere('username', 'LIKE', '%' . $input['keyword'] . '%')
                        ->orWhere('email', 'LIKE', '%' . $input['keyword'] . '%')
                        ->orWhere('role', 'LIKE', '%' . $input['keyword'] . '%');
            });
        }

        if (!empty($input['role'])) {
            $data->where('role', '=', $input['role']);
        }

        return $data->count();
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Application;
use App\Models\User;
use Illuminate\Support\Facades\Hash;
use App\Http\Requests\StoreUserRequest;
use App\Http\Requests\UpdateUserRequest;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $data['application'] = Application::first();

        $data['input'] = $this->getInputParameter($request);

        $data['input']['page'] = $data['input']['page'] < 1 ? 1 : $data['input']['page'];

        $data['input']['offset'] = $data['input']['page'] > 1 ? ($data['input']['page'] * 10) - 10 : 0;

        $data['number'] = $data['input']['offset'] + 1;

        $itemTotal = User::countData($data['input']);

        $data['pageTotal'] = intval(ceil($itemTotal / 10));

        $data['items'] = User::getData($data['input']);

        return view('pages.user.index', $data);
    }

    private function getInputParameter($request)
    {
        return [
            'page'=> intval($request->page),
            'order_by'=> $request->order_by,
            'order_direction'=> $request->order_direction,
            'keyword'=> $request->keyword,
            'role'=> $request->role,
        ];
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['application'] = Application::first();

        return view('pages.user.create', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreUserRequest $request)
    {
        $input = $request->validated();

        $input['password'] = Hash::make($input['password']);

        $input['created_at'] = time();

        User::create($input);

        return redirect('users')
                ->with('status', 'Berhasil menambah pengguna.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $data = [
            'item' => User::findOrFail($id),
            'application' => Application::first(),
        ];

        return view('pages.user.detail', $data);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data['application'] = Application::first();

        $data['item'] = User::findOrFail($id);

        return view('pages.user.edit', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateUserRequest $request, $id)
    {
        $data = User::findOrFail($id);

        $input = $request->validated();

        $input['updated_at'] = time();

        if (!empty($request->password)) {
            $input['password'] = Hash::make($request->password);
        }

        User::where('id', $id)->update($input);

        return redirect('users')
                ->with('status', 'Berhasil mengubah pengguna.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $data = User::findOrFail($id);

        $data->delete();

        return back()->with('status', 'Berhasil menghapus pengguna.');
    }
}

resources/views/pages/user/create.blade.php
@extends('layouts.dashboard')

@section('title', "$application->name - Pengguna - Tambah")

@section('description', 'Halaman yang berisi formulir untuk membuat data pengguna.')

@section('route_name', 'Tambah Pengguna')

@section('content')
    @if ($errors->any())
        <div class="alert alert-danger">
            <ul class="m-0">
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    <div class="card">
        <div class="card-header bg-white">
            Isi Formulir
        </div>
        <div class="card-body">
            <form action="{{ route('users.store') }}" method="POST">
                @csrf
                <div class="row align-items-center">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="name">Nama</label>
                            <input type="text" class="form-control" id="name" value="{{ old('name') }}" name="name">
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="username">Username</label>
                            <input type="text" class="form-control" id="username" value="{{ old('username') }}" name="username">
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="email">Email</label>
                            <input type="email" class="form-control" id="email" value="{{ old('email') }}" name="email">
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="password">Kata Sandi</label>
                            <input type="password" class="form-control" id="password" name="password">
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="role">Jenis</label>
                            <select name="role" id="role" class="form-control">
                                <option value="">-- Pilih --</option>
                                <option value="Admin"
                                    {{ old('role') === 'Admin' ? 'selected' : '' }}>
                                    Admin
                                </option>
                                <option value="Operator"
                                    {{ old('role') === 'Operator' ? 'selected' : '' }}>
                                    Operator
                                </option>
                            </select>
                        </div>
                    </div>
                    <div class="col-12">
                        <button type="submit" class="btn btn-primary">
                            Simpan
                        </button>
                        <a href="{{ url()->previous() }}" class="btn btn-secondary">
                            Kembali
                        </a>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/pages/user/detail.blade.php
@extends('layouts.dashboard')

@section('title', "$application->name - Pengguna - $item->name")

@section('description', 'Halaman yang berisi informasi detail Pengguna.')

@section('route_name', 'Detail Pengguna')

@section('content')
    <div class="card">
        <div class="card-header">
            <h5 class="m-0 text-dark">
                {{ $item->name }}
            </h5>
        </div>
        <div class="card-body">
            <div class="row mb-2">
                <div class="col-md-4 col-lg-3">
                    <b>Username <span class="d-md-none">:</span></b>
                </div>
                <div class="col-md-8 col-lg-9">
                    <b class="d-none d-md-inline">:</b> {{ $item->username }}
                </div>
            </div>
            <div class="row mb-2">
                <div class="col-md-4 col-lg-3">
                    <b>Email <span class="d-md-none">:</span></b>
                </div>
                <div class="col-md-8 col-lg-9">
                    <b class="d-none d-md-inline">:</b> {{ $item->email }}
                </div>
            </div>
            <div class="row mb-2">
                <div class="col-md-4 col-lg-3">
                    <b>Jenis <span class="d-md-none">:</span></b>
                </div>
                <div class="col-md-8 col-lg-9">
                    <b class="d-none d-md-inline">:</b> {{ $item->role }}
                </div>
            </div>
            <div class="row mb-2">
                <div class="col-md-4 col-lg-3">
                    <b>Tanggal Dibuat <span class="d-md-none">:</span></b>
                </div>
                <div class="col-md-8 col-lg-9">
                    <b class="d-none d-md-inline">:</b>
                    <span class="unix-column">
                        {{ $item->created_at }}
                    </span>
                </div>
            </div>
            <div class="row mb-2">
                <div class="col-md-4 col-lg-3">
                    <b>Tanggal Diubah <span class="d-md-none">:</span></b>
                </div>
                <div class="col-md-8 col-lg-9">
                    <b class="d-none d-md-inline">:</b>
                    <span class="unix-column">
                        {{ $item->created_at === $item->updated_at ? '-' : $item->updated_at }}
                    </span>
                </div>
            </div>
        </div>
        <div class="card-footer">
            <a href="{{ url()->previous() }}" class="btn btn-secondary">
                Kembali
            </a>
        </div>
    </div>
@endsection

resources/views/pages/user/edit.blade.php
@extends('layouts.dashboard')

@section('title', "$application->name - Pengguna - Ubah")

@section('description', 'Halaman yang berisi formulir untuk mengubah data pengguna.')

@section('route_name', 'Ubah Pengguna')

@section('content')
    @if ($errors->any())
        <div class="alert alert-danger">
            <ul class="m-0">
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    <div class="card">
        <div class="card-header bg-white">
            Isi Formulir
        </div>
        <div class="card-body">
            <form action="{{ route('users.update', $item->id) }}" method="POST">
                @method('PUT')
                @csrf
                <div class="row align-items-center">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="name">Nama</label>
                            <input type="text"
                                class="form-control"
                                id="name"
                                value="{{ empty(old('name')) ? $item->name : old('name') }}"
                                name="name">
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="username">Username</label>
                            <input type="text"
                                class="form-control"
                                id="username"
                                value="{{ empty(old('username')) ? $item->username : old('username') }}"
                                name="username">
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="email">Email</label>
                            <input type="email"
                                class="form-control"
                                id="email"
                                value="{{ empty(old('email')) ? $item->email : old('email') }}"
                                name="email">
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="password">Kata Sandi</label>
                            <input type="password" class="form-control" id="password" name="password"
                                placeholder="Tidak Wajib">
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="role">Jenis</label>
                            <select name="role" id="role" class="form-control">
                                <option value="">-- Pilih --</option>
                                <option value="Admin"
                                    {{ (empty(old('role')) && $item->role === 'Admin') || (!empty(old('role')) && old('role') === 'Admin') ? 'selected' : '' }}>
                                    Admin
                                </option>
                                <option value="Operator"
                                {{ (empty(old('role')) && $item->role === 'Operator') || (!empty(old('role')) && old('role') === 'Operator') ? 'selected' : '' }}>
                                    Operator
                                </option>
                            </select>
                        </div>
                    </div>
                    <div class="col-12">
                        <button type="submit" class="btn btn-primary">
                            Simpan
                        </button>
                        <a href="{{ url()->previous() }}" class="btn btn-secondary">
                            Kembali
                        </a>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection