routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\ForgotPasswordController;
use App\Http\Controllers\ResetPasswordController;
use App\Http\Controllers\LogoutController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\ChangePasswordController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\BrandController;
use App\Http\Controllers\UnitOfMeasurementController;
use App\Http\Controllers\ItemController;
use App\Http\Controllers\IncomeTransactionController;
use App\Http\Controllers\IncomeTransactionItemController;
use App\Http\Controllers\ExpenditureTransactionController;
use App\Http\Controllers\ExpenditureTransactionItemController;
use App\Http\Controllers\StockController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\ApplicationController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware(['guest'])->group(function () {
    Route::controller(LoginController::class)->group(function () {
        Route::get('', 'view')->name('login');
        Route::post('', 'authenticate')->middleware('throttle:5,1')
                                        ->name('authenticate');
    });

    Route::prefix('forgot-password')->group(function () {
        Route::controller(ForgotPasswordController::class)->group(function () {
            Route::get('', 'view')->name('forgot-password.index');
            Route::post('', 'sendEmail')->middleware('throttle:5,1')
                                        ->name('forgot-password.send');
        });
    });

    Route::prefix('reset-password')->group(function () {
        Route::controller(ResetPasswordController::class)->group(function () {
            Route::get('{token}', 'view')->name('reset-password.index');
            Route::post('', 'reset')->middleware('throttle:5,1')
                                    ->name('reset-password.reset');
        });
    });
});

Route::middleware(['auth'])->group(function () {
    Route::middleware(['can:isAdmin'])->group(function () {
        Route::resource('categories', CategoryController::class)->except([
            'show'
        ]);
    
        Route::resource('brands', BrandController::class)->except([
            'show'
        ]);
    
        Route::resource('unit-of-measurements', UnitOfMeasurementController::class)->except([
            'show'
        ]);
    
        Route::get('items/{id}/image', [ItemController::class, 'openImage']);

        Route::resource('users', UserController::class);

        Route::controller(ApplicationController::class)->group(function () {
            Route::get('application', 'edit')->name('application.edit');
            Route::put('application', 'update')->name('application.update');
        });
    });

    Route::post('logout', [LogoutController::class, 'logout'])
            ->name('logout');

    Route::get('dashboard', [DashboardController::class, 'index'])
            ->name('dashboard');

    Route::controller(ProfileController::class)->group(function () {
        Route::get('profile', 'edit')->name('profile.edit');
        Route::put('profile', 'update')->name('profile.update');
    });

    Route::controller(ChangePasswordController::class)->group(function () {
        Route::get('change-password', 'edit')->name('change-password.edit');
        Route::put('change-password', 'update')->name('change-password.update');
    });

    Route::resource('items', ItemController::class);
    
    Route::delete('income-transaction-items/{item_id}/create', [
        IncomeTransactionItemController::class, 'deleteCreateSession'
    ])->name('income-transaction-items.delete-create-session');

    Route::delete('income-transaction-items/{income_transaction_id}/{item_id}', [
        IncomeTransactionItemController::class, 'deleteEditSession'
    ])->name('income-transaction-items.delete-edit-session');

    Route::resource('income-transaction-items', IncomeTransactionItemController::class)->except([
        'show', 'index'
    ]);

    Route::resource('income-transactions', IncomeTransactionController::class);

    Route::delete('expenditure-transaction-items/{item_id}/create', [
        ExpenditureTransactionItemController::class, 'deleteCreateSession'
    ])->name('expenditure-transaction-items.delete-create-session');

    Route::delete('expenditure-transaction-items/{expenditure_transaction_id}/{item_id}', [
        ExpenditureTransactionItemController::class, 'deleteEditSession'
    ])->name('expenditure-transaction-items.delete-edit-session');

    Route::resource('expenditure-transaction-items', ExpenditureTransactionItemController::class)->except([
        'show', 'index', 'delete'
    ]);

    Route::resource('expenditure-transactions', ExpenditureTransactionController::class);

    Route::get('stocks', [StockController::class, 'index'])->name('stocks.index');
});

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'id'
    ];

    /**
     * Indicates if the model should be timestamped.
     *
     * @var bool
     */
    public $timestamps = false;

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'id' => 'string'
    ];

    public static function getData($input)
    {
        $data = self::select('id', 'name');

        if (!empty($input['keyword'])) {
            $data->where('id', 'LIKE', '%' . $input['keyword'] . '%')
                    ->orWhere('name', 'LIKE', '%' . $input['keyword'] . '%');
        }

        if ($input['order_by'] === 'name') {
            if ($input['order_direction'] !== 'asc' && $input['order_direction'] !== 'desc') {
                $data->orderBy($input['order_by']);
            } else {
                $data->orderBy($input['order_by'], $input['order_direction']);
            }
        } else {
            $data->orderBy('name', 'asc');
        }

        return $data->offset($input['offset'])
                        ->limit(10)
                        ->get();
    }

    public static function countData($input)
    {
        $data = self::select('id');

        if (!empty($input['keyword'])) {
            $data->where('name', 'like', "%" . $input['keyword'] . "%")
                    ->orWhere('id', 'like', "%" . $input['keyword'] . "%");
        }

        return $data->count();
    }

    /**
     * Get the items for the category.
     */
    public function comments()
    {
        return $this->hasMany(Item::class);
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Application;
use App\Models\Category;
use Illuminate\Support\Str;
use App\Http\Requests\StoreCategoryRequest;
use App\Http\Requests\UpdateCategoryRequest;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $data['application'] = Application::first();

        $data['input'] = $this->getInputParameter($request);

        $data['input']['page'] = $data['input']['page'] < 1 ? 1 : $data['input']['page'];

        $data['input']['offset'] = $data['input']['page'] > 1 ? ($data['input']['page'] * 10) - 10 : 0;

        $data['number'] = $data['input']['offset'] + 1;

        $itemTotal = Category::countData($data['input']);

        $data['pageTotal'] = intval(ceil($itemTotal / 10));

        $data['items'] = Category::getData($data['input']);

        return view('pages.category.index', $data);
    }

    private function getInputParameter($request)
    {
        return [
            'page'=> intval($request->page),
            'order_by'=> strval($request->order_by),
            'order_direction'=> strval($request->order_direction),
            'keyword'=> strval($request->keyword)
        ];
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['application'] = Application::first();

        $data['id'] = Str::uuid();

        return view('pages.category.create', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreCategoryRequest $request)
    {
        $input = $request->validated();

        Category::insertOrIgnore($input);

        return redirect('categories')
                ->with('status', 'Berhasil menambah kategori.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data['application'] = Application::first();

        $data['item'] = Category::findOrFail($id);

        return view('pages.category.edit', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateCategoryRequest $request, $id)
    {
        $data = Category::findOrFail($id);

        $input = $request->validated();

        Category::where('id', $id)->update($input);

        return redirect('categories')
                ->with('status', 'Berhasil mengubah kategori.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $data = Category::findOrFail($id);

        $data->delete();

        return back()->with('status', 'Berhasil menghapus kategori.');
    }
}

resources/views/pages/category/create.blade.php
@extends('layouts.dashboard')

@section('title', "$application->name - Kategori - Tambah")

@section('description', 'Halaman yang berisi formulir untuk membuat kategori.')

@section('route_name', 'Tambah Kategori')

@section('content')
    @if ($errors->any())
        <div class="alert alert-danger">
            <ul class="m-0">
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    <div class="card">
        <div class="card-header bg-white">
            Isi Formulir
        </div>
        <div class="card-body">
            <form action="{{ route('categories.store') }}" method="POST">
                @method('POST')
                @csrf
                <input type="hidden" name="id" value="{{ $id }}">
                <div class="row align-items-center">
                    <div class="col-md-2 col-lg-1">
                        <label for="name">
                            Nama
                        </label>
                    </div>
                    <div class="col-md-10 col-lg-11 mb-3">
                        <input type="text"
                            class="form-control"
                            name="name"
                            id="name"
                            value="{{ old('name') }}">
                    </div>
                    <div class="col-12 text-right">
                        <button type="submit" class="btn btn-primary">
                            Simpan
                        </button>
                        <a href="{{ url()->previous() }}" class="btn btn-secondary">
                            Kembali
                        </a>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/pages/category/edit.blade.php
@extends('layouts.dashboard')

@section('title', "$application->name - Kategori - Ubah")

@section('description', 'Halaman yang berisi formulir untuk mengubah kategori.')

@section('route_name', 'Ubah Kategori')

@section('content')
    @if ($errors->any())
        <div class="alert alert-danger">
            <ul class="m-0">
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    <div class="card">
        <div class="card-header bg-white">
            Isi Formulir
        </div>
        <div class="card-body">
            <form action="{{ route('categories.update', $item->id) }}" method="POST">
                @method('PUT')
                @csrf
                <div class="row align-items-center">
                    <div class="col-md-2 col-lg-1">
                        <label for="name">
                            Nama
                        </label>
                    </div>
                    <div class="col-md-10 col-lg-11 mb-3">
                        <input type="text"
                            class="form-control"
                            name="name"
                            id="name"
                            value="{{ empty(old('name')) ? $item->name : old('name') }}">
                    </div>
                    <div class="col-12 text-right">
                        <button type="submit" class="btn btn-primary">
                            Simpan
                        </button>
                        <a href="{{ url()->previous() }}" class="btn btn-secondary">
                            Kembali
                        </a>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/pages/category/index.blade.php
@extends('layouts.dashboard')

@section('title', "$application->name - Kategori")

@section('description', 'Halaman yang berisi daftar kategori yang dibuat.')

@section('route_name', 'Kategori')

@section('content')
    @if ($errors->any())
        <div class="alert alert-danger">
            <ul class="m-0">
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    @if (session('status'))
        <div class="alert alert-success alert-dismissible fade show">
            {{ session('status') }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    @endif
    <div class="row justify-content-end">
        <div class="col-auto">
            <a href="{{ route('categories.create') }}" class="btn btn-sm btn-primary mb-3">
                <i class="fas fa-plus mr-1"></i>
                Tambah
            </a>
        </div>
    </div>
    <div class="card">
        <div class="card-header bg-white">
            <div class="row justify-content-center justify-content-lg-between align-items-center">
                <div class="col-md-7 col-lg-4 col-xl-3 mb-2 mb-md-0">
                    <div class="row align-items-center justify-content-center">
                        <div class="col-md-auto">
                            <label for="sort" class="m-0 font-weight-bold">Urutan</label>
                        </div>
                        <div class="col p-md-0">
                            <select class="form-control form-control-sm" onchange="window.location.replace(this.value)">
                                <option value="{{ route('categories.index', ['order_by' => 'name', 'order_direction' => 'asc']) }}"
                                    {{ $input['order_by'] === 'name' && $input['order_direction'] === 'asc' ? 'selected' : '' }}>
                                    Nama (Menaik)
                                </option>
                                <option value="{{ route('categories.index', ['order_by' => 'name', 'order_direction' => 'asc']) }}"
                                    {{ $input['order_by'] === 'name' && $input['order_direction'] === 'asc' ? 'selected' : '' }}>
                                    Nama (Menurun)
                                </option>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="col-lg-auto col-md-5 col-lg-3">
                    <form action="{{ route('categories.index') }}" method="get">
                        <input type="hidden" name="order_by" value="{{ $input['order_by'] }}">
                        <input type="hidden" name="order_direction" value="{{ $input['order_direction'] }}">
                        <div class="input-group input-group-sm">
                            <input type="search"
                                class="form-control"
                                name="keyword"
                                id="q"
                                placeholder="Pencarian"
                                value="{{ empty($input['keyword']) ? '' : $input['keyword'] }}">
                            <div class="input-group-append">
                              <button class="btn btn-outline-secondary" type="submit" id="button-addon2">
                                <i class="fas fa-search"></i>
                              </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="card-body">
            <div class="table-responsive mb-3">
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th class="text-center" style="width: 2px">No</th>
                            <th class="text-center">ID</th>
                            <th>Nama</th>
                            <th class="text-center">Aksi</th>
                        </tr>
                    </thead>
                    <tbody>
                        @if ($items->isEmpty())
                            <tr>
                                <td class="text-center" colspan="4">
                                    Data tidak ditemukan.
                                </td>
                            </tr>
                        @else
                            @foreach ($items as $item)
                                <tr>
                                    <td class="text-center align-middle">
                                        {{ $number }}
                                    </td>
                                    <td class="text-center align-middle">
                                        {{ $item->id }}
                                    </td>
                                    <td class="align-middle">
                                        {{ $item->name }}
                                    </td>
                                    <td class="text-center align-middle">
                                        <a href="{{ route('categories.edit', $item->id) }}" class="btn btn-warning btn-sm my-1 my-lg-0">
                                            Ubah
                                        </a>
                                        <form action="{{ route('categories.destroy', $item->id) }}" method="post" class="d-inline my-1 my-lg-0">
                                            @csrf
                                            @method('DELETE')
                                            <button type="submit" class="btn btn-sm btn-danger" onclick="return confirm('Data lain yang menggunakan kategori ini akan ikut terhapus. Lanjutkan ?')">
                                                Hapus
                                            </button>
                                        </form>
                                    </td>
                                </tr>
                                @php
                                    $number++
                                @endphp
                            @endforeach
                        @endif
                    </tbody>
                </table>
            </div>

            <div class="row justify-content-end">
                <div class="col-auto">
                    <nav>
                        <ul class="pagination pagination-sm">
                            @if ($input['page'] === 1)
                                <li class="page-item disabled">
                                    <a href="" class="page-link"><<</a>
                                </li>

                                <li class="page-item disabled">
                                    <a href="" class="page-link"><</a>
                                </li>

                                <li class="page-item active">
                                    <a
                                        href="{{ route('categories.index', ['page' => 1, 'order_by' => $input['order_by'], 'order_direction' => $input['order_direction'], 'keyword' => $input['keyword']]) }}"
                                        class="page-link">
                                        1
                                    </a>
                                </li>

                                @for ($i = 2; $i <= $pageTotal; $i++)
                                    @if ($i < 4)
                                        <li class="page-item">
                                            <a class="page-link"
                                                href="{{ route('categories.index', ['page' => $i, 'order_by' => $input['order_by'], 'order_direction' => $input['order_direction'], 'keyword' => $input['keyword']]) }}">
                                                {{ $i }}
                                            </a>
                                        </li>
                                    @endif
                                @endfor

                                <li class="page-item">
                                    <a class="page-link"
                                        href="{{ route('categories.index', ['page' => $input['page'] + 1, 'order_by' => $input['order_by'], 'order_direction' => $input['order_direction'], 'keyword' => $input['keyword']]) }}">
                                        >
                                    </a>
                                </li>

                                <li class="page-item">
                                    <a class="page-link"
                                        href="{{ route('categories.index', ['page' => $pageTotal, 'order_by' => $input['order_by'], 'order_direction' => $input['order_direction'], 'keyword' => $input['keyword']]) }}">
                                        >>
                                    </a>
                                </li>
                            @else
                                <li class="page-item">
                                    <a class="page-link"
                                        href="{{ route('categories.index', ['page' => 1, 'order_by' => $input['order_by'], 'order_direction' => $input['order_direction'], 'keyword' => $input['keyword']]) }}">
                                        <<
                                    </a>
                                </li>

                                <li class="page-item">
                                    <a class="page-link"
                                        href="{{ route('categories.index', ['page' => $input['page'] - 1, 'order_by' => $input['order_by'], 'order_direction' => $input['order_direction'], 'keyword' => $input['keyword']]) }}">
                                        <
                                    </a>
                                </li>

                                @php
                                    $pageStartNumber = $input['page'] !== $pageTotal ? $input['page'] - 1 : $input['page'] - 2;
                                    $loopingNumberStop = $input['page'] !== $pageTotal ? $input['page'] + 1 : $input['page'];
                                    $pageStartNumber = $pageStartNumber < 1 ? 1 : $pageStartNumber;
                                @endphp

                                @for ($i = $pageStartNumber; $i <= $loopingNumberStop; $i++)
                                    <li class="page-item {{ $input['page'] === $i ? 'active' : '' }}">
                                        <a class="page-link"
                                            href="{{ route('categories.index', ['page' => $i, 'order_by' => $input['order_by'], 'order_direction' => $input['order_direction'], 'keyword' => $input['keyword']]) }}">
                                            {{ $i }}
                                        </a>
                                    </li>
                                @endfor

                                <li class="page-item {{ $input['page'] === $pageTotal ? 'disabled' : '' }}">
                                    <a class="page-link"
                                        href="{{ route('categories.index', ['page' => $input['page'] + 1, 'order_by' => $input['order_by'], 'order_direction' => $input['order_direction'], 'keyword' => $input['keyword']]) }}">
                                        >
                                    </a>
                                </li>

                                <li class="page-item {{ $input['page'] === $pageTotal ? 'disabled' : '' }}">
                                    <a class="page-link"
                                        href="{{ route('categories.index', ['page' => $pageTotal, 'order_by' => $input['order_by'], 'order_direction' => $input['order_direction'], 'keyword' => $input['keyword']]) }}">
                                        >>
                                    </a>
                                </li>
                            @endif
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </div>
@endsection