routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\ForgotPasswordController;
use App\Http\Controllers\ResetPasswordController;
use App\Http\Controllers\LogoutController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\ChangePasswordController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\BrandController;
use App\Http\Controllers\UnitOfMeasurementController;
use App\Http\Controllers\ItemController;
use App\Http\Controllers\IncomeTransactionController;
use App\Http\Controllers\IncomeTransactionItemController;
use App\Http\Controllers\ExpenditureTransactionController;
use App\Http\Controllers\ExpenditureTransactionItemController;
use App\Http\Controllers\StockController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\ApplicationController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware(['guest'])->group(function () {
    Route::controller(LoginController::class)->group(function () {
        Route::get('', 'view')->name('login');
        Route::post('', 'authenticate')->middleware('throttle:5,1')
                                        ->name('authenticate');
    });

    Route::prefix('forgot-password')->group(function () {
        Route::controller(ForgotPasswordController::class)->group(function () {
            Route::get('', 'view')->name('forgot-password.index');
            Route::post('', 'sendEmail')->middleware('throttle:5,1')
                                        ->name('forgot-password.send');
        });
    });

    Route::prefix('reset-password')->group(function () {
        Route::controller(ResetPasswordController::class)->group(function () {
            Route::get('{token}', 'view')->name('reset-password.index');
            Route::post('', 'reset')->middleware('throttle:5,1')
                                    ->name('reset-password.reset');
        });
    });
});

Route::middleware(['auth'])->group(function () {
    Route::middleware(['can:isAdmin'])->group(function () {
        Route::resource('categories', CategoryController::class)->except([
            'show'
        ]);
    
        Route::resource('brands', BrandController::class)->except([
            'show'
        ]);
    
        Route::resource('unit-of-measurements', UnitOfMeasurementController::class)->except([
            'show'
        ]);
    
        Route::get('items/{id}/image', [ItemController::class, 'openImage']);

        Route::resource('users', UserController::class);

        Route::controller(ApplicationController::class)->group(function () {
            Route::get('application', 'edit')->name('application.edit');
            Route::put('application', 'update')->name('application.update');
        });
    });

    Route::post('logout', [LogoutController::class, 'logout'])
            ->name('logout');

    Route::get('dashboard', [DashboardController::class, 'index'])
            ->name('dashboard');

    Route::controller(ProfileController::class)->group(function () {
        Route::get('profile', 'edit')->name('profile.edit');
        Route::put('profile', 'update')->name('profile.update');
    });

    Route::controller(ChangePasswordController::class)->group(function () {
        Route::get('change-password', 'edit')->name('change-password.edit');
        Route::put('change-password', 'update')->name('change-password.update');
    });

    Route::resource('items', ItemController::class);
    
    Route::delete('income-transaction-items/{item_id}/create', [
        IncomeTransactionItemController::class, 'deleteCreateSession'
    ])->name('income-transaction-items.delete-create-session');

    Route::delete('income-transaction-items/{income_transaction_id}/{item_id}', [
        IncomeTransactionItemController::class, 'deleteEditSession'
    ])->name('income-transaction-items.delete-edit-session');

    Route::resource('income-transaction-items', IncomeTransactionItemController::class)->except([
        'show', 'index'
    ]);

    Route::resource('income-transactions', IncomeTransactionController::class);

    Route::delete('expenditure-transaction-items/{item_id}/create', [
        ExpenditureTransactionItemController::class, 'deleteCreateSession'
    ])->name('expenditure-transaction-items.delete-create-session');

    Route::delete('expenditure-transaction-items/{expenditure_transaction_id}/{item_id}', [
        ExpenditureTransactionItemController::class, 'deleteEditSession'
    ])->name('expenditure-transaction-items.delete-edit-session');

    Route::resource('expenditure-transaction-items', ExpenditureTransactionItemController::class)->except([
        'show', 'index', 'delete'
    ]);

    Route::resource('expenditure-transactions', ExpenditureTransactionController::class);

    Route::get('stocks', [StockController::class, 'index'])->name('stocks.index');
});

app/Http/Controllers/IncomeTransactionController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Application;
use App\Models\IncomeTransaction;
use App\Models\IncomeTransactionItem;
use App\Models\Item;
use Illuminate\Support\Str;
use App\Http\Requests\StoreIncomeTransactionRequest;
use App\Http\Requests\UpdateIncomeTransactionRequest;

class IncomeTransactionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $data['application'] = Application::first();

        $data['input'] = $this->getInputParameter($request);

        $data['input']['page'] = $data['input']['page'] < 1 ? 1 : $data['input']['page'];

        $data['input']['offset'] = $data['input']['page'] > 1 ? ($data['input']['page'] * 10) - 10 : 0;

        $data['number'] = $data['input']['offset'] + 1;

        $itemTotal = IncomeTransaction::countData($data['input']);

        $data['pageTotal'] = intval(ceil($itemTotal / 10));

        $data['items'] = IncomeTransaction::getData($data['input']);

        $request->session()->forget([
            'create-income-transaction-item', 'edit-income-transaction-item'
        ]);

        return view('pages.income-transaction.index', $data);
    }

    private function getInputParameter($request)
    {
        return [
            'page'=> intval($request->page),
            'order_by'=> strval($request->order_by),
            'order_direction'=> strval($request->order_direction),
            'keyword'=> strval($request->keyword),
            'start_date' => intval($request->start_date),
            'end_date' => intval($request->end_date),
            'string_start_date' => strval($request->string_start_date),
            'string_end_date' => strval($request->string_end_date)
        ];
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data = [
            'application' => Application::first(),
            'items' => Item::orderBy('description')->get(),
            'income_transaction_items' => IncomeTransactionItem::getWithSession(
                session('create-income-transaction-item')
            )
        ];

        return view('pages.income-transaction.create', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreIncomeTransactionRequest $request)
    {
        $input = $request->validated();

        $incomeTransaction = IncomeTransaction::create($input);

        $incomeTransaction->incomeTransactionItems()->createMany(
            $request->session()->get('create-income-transaction-item')
        );

        return redirect('income-transactions')
                ->with('status', 'Berhasil menambah transaksi (masuk).');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $data = [
            'item' => IncomeTransaction::with('incomeTransactionItems.item.unitOfMeasurement')->findOrFail($id), 
            'application' => Application::first()
        ];

        $data['subitems'] = $data['item']->incomeTransactionItems->sortBy('item.description');

        return view('pages.income-transaction.detail', $data);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $session = session('edit-income-transaction-item');

        $findAllData = false;

        if (!empty($session)) {
            if ($session['id'] != $id) {
                $request->session()->forget('edit-income-transaction-item');
                $findAllData = true;
            } else {
                $findAllData = false;
            }
        } else {
            $findAllData = true;
        }

        if ($findAllData) {
            $data['item'] = IncomeTransaction::with(
                'incomeTransactionItems.item.unitOfMeasurement'
            )
            ->findOrFail($id);
        } else {
            $data['item'] = IncomeTransaction::findOrFail($id);
        }

        $data['application'] = Application::first();

        $data['items'] = Item::orderBy('description')->get();

        return view('pages.income-transaction.edit', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateIncomeTransactionRequest $request, $id)
    {
        $data = IncomeTransaction::findOrFail($id);

        $input['income_transaction'] = $request->validated();

        $session = $request->session()->get('edit-income-transaction-item');

        IncomeTransaction::where('id', $id)->update($input['income_transaction']);

        if (!empty($session)) {
            $input['income_transaction_items'] = [];

            foreach ($session['incomeTransactionItems'] as $key => $value) {
                array_push($input['income_transaction_items'], new IncomeTransactionItem([
                    'item_id' => $value['item_id'],
                    'amount' => $value['amount']
                ]));
            }

            IncomeTransactionItem::where('income_transaction_id', $id)->delete();

            $data->incomeTransactionItems()->saveMany($input['income_transaction_items']);
        }

        return redirect('income-transactions')
                ->with('status', 'Berhasil mengubah transaksi (masuk).');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $data = IncomeTransaction::findOrFail($id);

        $data->delete();

        return back()->with('status', 'Berhasil menghapus transaksi (masuk).');
    }
}

resources/views/pages/income-transaction/create.blade.php
@extends('layouts.dashboard')

@section('title', "$application->name - Transaksi (Masuk) - Tambah")

@section('description', 'Halaman yang berisi formulir untuk membuat data transaksi pemasukkan.')

@section('route_name', 'Tambah Transaksi (Masuk)')

@section('content')
    @if ($errors->any())
        <div class="alert alert-danger">
            <ul class="m-0">
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    @if (session('status'))
        <div class="alert alert-success alert-dismissible fade show">
            {{ session('status') }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    @endif
    <ul class="nav nav-tabs bg-white" id="myTab" role="tablist">
        <li class="nav-item" role="presentation">
          <button class="nav-link active" id="home-tab" data-toggle="tab" data-target="#home" type="button" role="tab" aria-controls="home" aria-selected="true">Barang</button>
        </li>
        <li class="nav-item" role="presentation">
            <button class="nav-link" id="selected-tab" data-toggle="tab" data-target="#selected" type="button" role="tab" aria-controls="selected" aria-selected="false">Terpilih</button>
        </li>
        <li class="nav-item" role="presentation">
          <button class="nav-link" id="profile-tab" data-toggle="tab" data-target="#profile" type="button" role="tab" aria-controls="profile" aria-selected="false">Transaksi</button>
        </li>
    </ul>
    <div class="tab-content" id="myTabContent">
        <div class="tab-pane fade show active bg-white border p-2 px-3" id="home" role="tabpanel">
            <form action="{{ route('income-transaction-items.store') }}" method="post">
                @csrf
                <div class="row">
                    <div class="col-md-10">
                        <div class="form-group">
                            <select name="item_id" id="item_id" class="form-control">
                                <option value="">-- Pilih Barang --</option>
                                @foreach ($items as $item)
                                    <option value="{{ $item->id }}" {{ old('item_id') === $item->id ? 'selected' : '' }}>
                                        {{ $item->description }}
                                        ({{ $item->part_number }})
                                    </option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="col-md-2">
                        <div class="form-group">
                            <input type="number" class="form-control" id="amount" name="amount" placeholder="Jumlah" value="{{ old('amount') }}" min="1">
                        </div>
                    </div>
                    <div class="col-12 text-right">
                        <a href="{{ route('income-transactions.index') }}" class="btn btn-secondary">
                            Kembali
                        </a>
                        <button class="btn btn-primary" type="submit">
                            Tambah
                        </button>
                    </div>
                </div>
            </form>
        </div>
        <div class="tab-pane fade p-2 px-3 bg-white border" id="selected" role="tabpanel">
            <div class="table-responsive">
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>Nomor Unik</th>
                            <th>Deskripsi</th>
                            <th>Satuan Barang</th>
                            <th class="text-center">Jumlah</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @if (empty($income_transaction_items))
                            <tr>
                                <td colspan="5" class="text-center">Barang belum dipilih.</td>
                            </tr>
                        @else
                            @foreach ($income_transaction_items as $item)
                                <tr>
                                    <td class="align-middle">
                                        {{ $item->part_number }}
                                    </td>
                                    <td class="align-middle">
                                        {{ $item->description }}
                                    </td>
                                    <td class="align-middle">
                                        {{ $item->short_name }}
                                    </td>
                                    <td class="align-middle text-center">
                                        {{ currency($item->amount) }}
                                    </td>
                                    <td class="align-middle text-center">
                                        <form action="{{ url("income-transaction-items/$item->id/create") }}" method="post" class="d-inline">
                                            @csrf
                                            @method('DELETE')
                                            <button type="submit" class="btn btn-danger btn-sm">
                                                Hapus
                                            </button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                        @endif
                    </tbody>
                </table>
            </div>
            <div class="text-right">
                <a href="{{ route('income-transactions.index') }}" class="btn btn-secondary">
                    Kembali
                </a>
            </div>
        </div>
        <div class="tab-pane fade p-2 px-3 bg-white border" id="profile" role="tabpanel">
            <form class="row" action="{{ route('income-transactions.store') }}" method="POST">
                @csrf
                @method('POST')
                <div class="col-md-6 col-lg-4">
                    <div class="form-group">
                        <label for="html_created_at">Tanggal</label>
                        <input type="datetime-local"
                            class="form-control"
                            id="html_created_at"
                            name="html_created_at"
                            onkeyup="document.getElementById('created_at').value = +new Date(this.value) / 1000"
                            onchange="document.getElementById('created_at').value = +new Date(this.value) / 1000"
                            data-value="{{ empty(old('created_at')) ? time() : old('created_at') }}">
                        <input type="hidden"
                            name="created_at"
                            id="created_at"
                            value="{{ empty(old('created_at')) ? time() : old('created_at') }}">
                    </div>
                </div>
                <div class="col-md-6 col-lg-4">
                    <div class="form-group">
                        <label for="reference_number">Nomor Referensi</label>
                        <input type="text"
                            name="reference_number"
                            id="reference_number"
                            value="{{ old('reference_number') }}"
                            class="form-control">
                    </div>
                </div>
                <div class="col-md-6 col-lg-4">
                    <div class="form-group">
                        <label for="supplier">Pemasok</label>
                        <input type="text"
                            class="form-control"
                            id="supplier"
                            name="supplier"
                            value="{{ old('supplier') }}">
                    </div>
                </div>
                <div class="col-12">
                    <div class="form-group">
                        <label for="remarks">Catatan</label>
                        <textarea name="remarks" id="remarks" class="form-control">{{ old('remarks') }}</textarea>
                    </div>
                </div>
                <div class="col-12 text-right">
                    <a href="{{ route('income-transactions.index') }}" class="btn btn-secondary">
                        Kembali
                    </a>
                    <button type="submit"
                        class="btn btn-primary">
                        Simpan
                    </button>
                </div>
            </form>
        </div>
    </div>
    <script>
        function datetimeLocal(unix) {
            var dt = new Date(unix * 1000);
            dt.setMinutes(dt.getMinutes() - dt.getTimezoneOffset());
            return dt.toISOString().slice(0, 16);
        }

        var htmlCreatedAt = document.getElementById('html_created_at'),
            unix = parseInt(htmlCreatedAt.getAttribute('data-value')),
            date = datetimeLocal(unix);

        htmlCreatedAt.value = date;
    </script>
@endsection

resources/views/pages/income-transaction/detail.blade.php
@extends('layouts.dashboard')

@section('title', "$application->name - Transaksi Masuk - $item->reference_number")

@section('description', 'Halaman yang berisi informasi detail transaksi masuk.')

@section('route_name', 'Detail Transaksi Masuk')

@section('content')
    <div class="card">
        <div class="card-header">
            <h5 class="m-0 text-dark">
                {{ $item->reference_number }}
            </h5>
        </div>
        <div class="card-body">
            <div class="row mb-2">
                <div class="col-md-4 col-lg-3">
                    <b>Pemasok <span class="d-md-none">:</span></b>
                </div>
                <div class="col-md-8 col-lg-9">
                    <b class="d-none d-md-inline">:</b> {{ $item->supplier }}
                </div>
            </div>
            <div class="row mb-2">
                <div class="col-md-4 col-lg-3">
                    <b>Catatan <span class="d-md-none">:</span></b>
                </div>
                <div class="col-md-8 col-lg-9">
                    <b class="d-none d-md-inline">:</b> {{ $item->remarks }}
                </div>
            </div>
            <div class="row">
                <div class="col-12 text-center">
                    <b>Daftar Barang</b>
                    <div class="table-responsive mt-2">
                        <table class="table table-bordered">
                            <thead>
                                <tr>
                                    <th class="align-middle">No</th>
                                    <th class="align-middle text-left">Nomor Unik</th>
                                    <th class="align-middle text-left">Deskripsi</th>
                                    <th class="align-middle">Satuan</th>
                                    <th class="align-middle text-right">Jumlah</th>
                                </tr>
                            </thead>
                            <tbody>
                                @php
                                    $number = 1;
                                    $itemTotal = 0;
                                @endphp
                                @foreach ($subitems as $incomeTransactionItem)
                                    <tr>
                                        <td class="align-middle">
                                            {{ $number }}
                                        </td>
                                        <td class="align-middle text-left">
                                            {{ $incomeTransactionItem->item->part_number }}
                                        </td>
                                        <td class="align-middle text-left">
                                            {{ $incomeTransactionItem->item->description }}
                                        </td>
                                        <td class="align-middle">
                                            {{ $incomeTransactionItem->item->unitOfMeasurement->full_name }}
                                        </td>
                                        <td class="align-middle text-right">
                                            {{ currency($incomeTransactionItem->amount) }}
                                        </td>
                                    </tr>
                                    @php
                                        $number++;
                                        $itemTotal += $incomeTransactionItem->amount;
                                    @endphp
                                @endforeach
                            </tbody>
                            <tfoot>
                                <tr>
                                    <th colspan="4" class="text-right">
                                        Total Barang
                                    </th>
                                    <th class="text-right">
                                        {{ currency($itemTotal) }}
                                    </th>
                                </tr>
                            </tfoot>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <div class="card-footer text-right">
            <a href="{{ url()->previous() }}" class="btn btn-secondary">
                Kembali
            </a>
        </div>
    </div>
@endsection